### ISSUE TITLE
Wrong :path for nested resources

### ISSUE THREAD

**Issue by dkonovalchuk** [mgwidmann/scrivener_html#14] opened 2016-03-29 22:40 UTC
Hi,

In my router.ex I have some nested resources, for example: 
```elixir
scope "/admin", MyApp do
  scope "/nested", as: :nested do
    resources "/users", Nested.UserController
  end
end
```

When I use pagination_links function like that `pagination_links @conn, @page`, I'm getting an error `undefined function MyApp.Router.Helpers.user_path/3`, because correct path should be `MyApp.Router.Helpers.nested_user_path/3`. 
To make it work I have to use additional `:path` argument to `pagination_links` like that
`pagination_links @conn, @page, path: &nested_user_path(&1, &2, &3)`.
It would be nice to have nested resources `:as` argument to be included into the path by default, without using that additional `:path` argument.

Thanks!

**Comment by mgwidmann** [comment] 2016-03-30 13:52
Can you show an example call to `pagination_links` in the way you are suggesting?

**Comment by mgwidmann** [comment] 2016-03-30 13:53
By the way, you should be able to just do `path: &nested_user_path/3` instead of what you showed above.

**Comment by dkonovalchuk** [comment] 2016-03-30 14:09
@mgwidmann I was expecting to include `:as` argument into the path by default. In my example call to `pagination_links @conn, @page` on nested user's index template page, I was expecting to use `nested_user_path` instead of  `user_path` on page links.
And thanks for the `path: &nested_user_path/3`.

**Comment by mgwidmann** [comment] 2016-03-30 14:21
Are you suggesting something like:

```elixir
<%= pagination_links @conn, @page, as: :nested %>
```

Which should prepend `nested_` to the route generated?

**Comment by dkonovalchuk** [comment] 2016-03-30 17:14
@mgwidmann please check the code from router.ex I provided:
```elixir
scope "/admin", MyApp do
  scope "/nested", as: :nested do
    resources "/users", Nested.UserController
  end
end
```
`as: :nested` is already present in here, so I expect `<%= pagination_links @conn, @page %>` to generate pagination links with correct nested path without including additional `:as` argument in the function call. 
If you check `inspect @conn.path_info` on that nested user's index page, it will be `["nested", "users"]`, not just `["users"]`. I hope you could just make a correct path using this `@conn.path_info` if you have access to @conn.

**Comment by mgwidmann** [comment] 2016-03-30 21:17
Hmmm, thats the current path info. Thats not how its being done at the moment. I'd have to think how that would work for multiple pagination link calls on the same page.

**Comment by mgwidmann** [comment] 2016-04-15 13:30
Coming back to this, I'm not sure how to get the scope information without requiring the path parameter. Same as when you use `as: :something`, we will guess the wrong function name. If anyone has an idea on how to get that information, to read the router data at runtime, I'll happily accept a PR. Otherwise I plan to close this issue since its working as intended (thats the purpose of the `path` parameter).

**Closed** 2016-05-24 16:02 UTC
Labels: help wanted, workaround
